"""Initial_migration

Revision ID: bf739214c8fe
Revises: 
Create Date: 2025-12-08 01:55:32.745813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf739214c8fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_external_id'), 'clients', ['external_id'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('crm_thread_id', sa.String(length=255), nullable=False),
    sa.Column('customer_external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'ARCHIVED', name='conversationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_client_id'), 'conversations', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversations_crm_thread_id'), 'conversations', ['crm_thread_id'], unique=True)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('agent_state',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('ai_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXECUTED', 'CANCELLED', name='actionstatus'), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('policy_result', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Enum('AI', 'HUMAN', name='createdby'), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('crm_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_actions_client_id'), 'ai_actions', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_conversation_id'), 'ai_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_created_at'), 'ai_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_actions_status'), 'ai_actions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_actions_type'), 'ai_actions', ['type'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('crm_message_id', sa.String(length=255), nullable=True),
    sa.Column('request_role', sa.String(length=50), nullable=False),
    sa.Column('request_summary', sa.Text(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('openai_response_id', sa.String(length=255), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_runs_client_id'), 'ai_runs', ['client_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_conversation_id'), 'ai_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_runs_created_at'), 'ai_runs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_runs_created_at'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_conversation_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_client_id'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_ai_actions_type'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_status'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_created_at'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_conversation_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_client_id'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_table('agent_state')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_crm_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_client_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_external_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
