"""add_policies_column

Revision ID: eea23c57c3c7
Revises: bf739214c8fe
Create Date: 2025-12-15 00:34:37.077859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea23c57c3c7'
down_revision: Union[str, None] = 'bf739214c8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('policies', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'policies')
    # ### end Alembic commands ###
